// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsFeeSystem.Data;

#nullable disable

namespace StudentsFeeSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250415053234_sixToTwelveClassAdded")]
    partial class sixToTwelveClassAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("StudentsFeeSystem.Models.FeeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToClass10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToClass11")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToClass12")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToClass6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToClass7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToClass8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToClass9")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToFemale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssignedToMale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeeItems");
                });

            modelBuilder.Entity("StudentsFeeSystem.Models.GenderFeeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeeItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeeItemId");

                    b.ToTable("GenderFeeAssignments");
                });

            modelBuilder.Entity("StudentsFeeSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Department")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Roll")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentsFeeSystem.Models.GenderFeeAssignment", b =>
                {
                    b.HasOne("StudentsFeeSystem.Models.FeeItem", "FeeItem")
                        .WithMany("GenderAssignments")
                        .HasForeignKey("FeeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeItem");
                });

            modelBuilder.Entity("StudentsFeeSystem.Models.FeeItem", b =>
                {
                    b.Navigation("GenderAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
