// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsFeeSystem.Data;

#nullable disable

namespace StudentsFeeSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250408172627_UpdatedToNew")]
    partial class UpdatedToNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("StudentsFeeSystem.Models.Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("StudentsFeeSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Department")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Roll")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentsFeeSystem.Models.StudentFee", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "FeeId");

                    b.HasIndex("FeeId");

                    b.ToTable("StudentsFee");
                });

            modelBuilder.Entity("StudentsFeeSystem.Models.StudentFee", b =>
                {
                    b.HasOne("StudentsFeeSystem.Models.Fee", "Fee")
                        .WithMany()
                        .HasForeignKey("FeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentsFeeSystem.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
